services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:  
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/test
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test
    healthcheck:
      test:  perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 40s
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
  app: 
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on: 
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment: 
      - NEO4J_HOST=bolt://neo4j
      - NEO4J_USERNAME=neo4j 
      - NEO4J_PASSWORD=test
      - NEO4J_DATABASE=neo4j
      - REDIS_HOST=redis 
      - REDIS_PORT=6379

       